baseURL = "https://chong-one.vercel.app/"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring-light"
title = "Chong's Chasma"
[markup.goldmark.renderer]
unsafe = true
